export const data = [
  {
    id: '0',
    name: 'Terra',
    image: require('../assets/Earth.png'),
    imageBig: require('../assets/Earth-big.png'),
    style: 'earthStyle',
    moons: '1',
    age: '4.5',
    temperature: '15',
    description:
      'Terceiro planeta do sistema solar a partir do Sol, o planeta Terra é rochoso, com atmosfera gasosa e temperatura média de 15°C. Possui um satélite natural, a Lua, e a quantidade de água existente no planeta, também chamado de “planeta azul”, aliada à quantidade de oxigênio, permitem o desenvolvimento da vida no planeta, sendo o único conhecido do sistema solar com vida humana.',
    link: 'https://www.todamateria.com.br/planeta-terra/',
  },
  {
    id: '1',
    name: 'Marte',
    image: require('../assets/Mars.png'),
    imageBig: require('../assets/Mars-big.png'),
    style: 'marsStyle',
    moons: '2',
    age: '4.6',
    temperature: '22',
    description:
      'Quarto planeta a partir do Sol e o mais visível do planeta Terra, Marte possui dois satélites naturais “Fobos e Deimos”, sendo o segundo menor planeta do sistema solar, atrás de Mercúrio. Também chamado de “planeta vermelho”, devido às partículas de óxido de ferro presentes em sua atmosfera, o planeta Marte é um planeta rochoso, frio e seco.',
    link: 'hhttps://www.todamateria.com.br/planeta-marte/',
  },
  {
    id: '2',
    name: 'Mercúrio',
    image: require('../assets/Mercury.png'),
    imageBig: require('../assets/Mercury-big.png'),
    style: 'mercuryStyle',
    moons: '0',
    age: '4.5',
    temperature: '400',
    description:
      'Mercúrio é o planeta mais próximo do Sol. É um planeta rochoso, destituído de satélites e atmosfera rarefeita, sendo também o menor planeta do sistema solar. Por esse motivo apresenta temperaturas bastante elevadas de aproximadamente 400°C. Por outro lado, a face do planeta não iluminada pelo sol pode atingir temperaturas de aproximadamente -170 °C. O movimento de rotação do planeta é de 59 dias, enquanto o de translação é de 87 dias.',
    link: 'https://www.todamateria.com.br/planeta-mercurio/',
  },
  {
    id: '3',
    name: 'Saturno',
    image: require('../assets/Saturn.png'),
    imageBig: require('../assets/Saturn-big.png'),
    style: 'saturnStyle',
    moons: '82',
    age: '4.5',
    temperature: '-138',
    description:
      'Segundo maior planeta do sistema solar, depois de Júpiter, Saturno é conhecido pelos seus anéis, formados por rocha, gelo e poeira. Sexto planeta a partir do sol, depois de Júpiter, Saturno é o planeta do sistema solar que possui muitos satélites: 82 luas.',
    link: 'https://www.todamateria.com.br/planeta-saturno/',
  },
  {
    id: '4',
    name: 'Júpiter',
    image: require('../assets/Jupyter.png'),
    imageBig: require('../assets/Jupyter-big.png'),
    style: 'jupyterStyle',
    moons: '79',
    age: '4.6',
    temperature: '-150',
    description:
      'Júpiter é o maior planeta do sistema solar. É um planeta gasoso (composto sobretudo por hidrogênio), 1.300 vezes maior do que o planeta Terra. Quinto planeta a partir do Sol, Júpiter possui o maior número de satélites, 79 satélites, e apresenta temperaturas de até -150°C',
    link: 'https://www.todamateria.com.br/planeta-jupiter/',
  },
  {
    id: '5',
    name: 'Vênus',
    image: require('../assets/Venus.png'),
    imageBig: require('../assets/Venus-big.png'),
    style: 'venusStyle',
    moons: '14',
    age: '4.5',
    temperature: '484',
    description:
      'Conhecido como “Estrela d’alva”, por causa de seu forte brilho, Vênus tal qual Mercúrio é um planeta que não possui satélite. Visível do nosso planeta, Vênus é o segundo planeta a partir do Sol e o mais perto do planeta Terra. Curioso notar que mesmo sendo o segundo planeta a partir do Sol (depois de Mercúrio), Vênus é o planeta mais quente do sistema solar, com temperaturas que podem atingir 480°C. Assemelha-se com o planeta Terra no tocante ao tamanho, composição, estrutura, massa, densidade e força gravitacional.',
    link: 'https://www.todamateria.com.br/planeta-venus/',
  },
  {
    id: '6',
    name: 'Urano',
    image: require('../assets/Uranus.png'),
    imageBig: require('../assets/Uranus-big.png'),
    style: 'uranusStyle',
    moons: '27',
    age: '4.6',
    temperature: '-185',
    description:
      'Terceiro maior planeta do sistema solar e sétimo planeta a partir do Sol, Urano é um planeta gasoso que apresenta médias de temperatura de -185°C e possui 27 satélites. Possui uma característica interessante tocante ao seu eixo de rotação com quase noventa graus em relação com o plano de sua órbita, que por sua vez é muito extensa.',
    link: 'https://www.todamateria.com.br/planeta-jupiter/',
  },
  {
    id: '7',
    name: 'Netuno',
    image: require('../assets/Neptune.png'),
    imageBig: require('../assets/Neptune-big.png'),
    style: 'neptuneStyle',
    moons: '14',
    age: '4.5',
    temperature: '-200',
    description:
      'Planeta do sistema solar mais distante do Sol e o quarto maior em tamanho, Netuno possui 14 satélites naturais e apresenta temperaturas médias de aproximadamente -200°C. Trata-se de um planeta gasoso, formado principalmente por hidrogênio, hélio, amônia, metano e água. O movimento de rotação do planeta dura cerca de 16 horas, enquanto sua translação equivale a 164 anos terrestres.',
    link: 'https://www.todamateria.com.br/planeta-netuno/',
  },
];
